version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: TurnstileSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:management"
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  myapp:
    image: wepapi:latest 
    container_name: wepapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=mydatabase;Username=myuser;Password=mypassword
      RabbitMQ__Host: rabbitmq
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
